### ISSUE TITLE
An "Author" section

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepspec#13]
One of the review comments is:

> Data citation (giving credit) is an important part of open science practice. Do you plan to explicitly support or model these kinds of relations in you configuration files, especially with project modifiers and re-combination of PEPs?

I was wondering if we should add an 'author' block in the pep specification. Or, perhaps this should be an extension and we can write a separate tool that reads and parses such an authorship block?

Thoughts @afrendeiro or @johanneskoester?

**Comment by afrendeiro** [comment]
I think this is a good point, important for attribution and for traceability as datasets age as well.
It should be more than a simple `author` field though. Maybe an `authorship` block with fields like `author` but also IDs like a `doi` would be important. Affiliations or emails/arbitrary urls would also be useful, but they can change.
Leaning towards integration in the spec, so it would need to be well thought.

**Comment by nsheff** [comment]
Well, here's an example of yaml metadata for an author block I use in [sciquill](http://sciquill.databio.org), which is what we used for the PEP paper:

```
author:
- name: Nathan C. Sheffield
  affiliation: "1,2,3,4"
  correspondence: "nsheffield@virginia.edu"
  orcid: 0000-0001-5643-4068
- name: Michał Stolarczyk
  affiliation: 1
  orcid: 0000-0003-2101-9061
- name: Vincent P. Reuter
  affiliation: 1,5
  orcid: 0000-0002-7967-976X
- name: André F. Rendeiro
  orcid: 0000-0001-9362-5373
  affiliation: 6,7
institutions:
- name: Center for Public Health Genomics, University of Virginia
  key: 1
- name: Department of Public Health Sciences, University of Virginia
  key: 2
- name: Department of Biomedical Engineering, University of Virginia
  key: 3
- name: Department of Biochemistry and Molecular Genetics, University of Virginia
  key: 4
- name: Genomics and Computational Biology Graduate Group, University of Pennsylvania
  key: 5 
- name: Institute for Computational Biomedicine, Weill Cornell Medical College
  key: 6
- name: Caryl and Israel Englander Institute for Precision Medicine, Weill Cornell Medical College
  key: 7
```

I hadn't thought of authorship on a PEP in this way, but maybe this could actually be a universal authorship specification. I am not aware of something like this already existing.
