### ISSUE TITLE
confusing section of the project config file specification

### ISSUE THREAD

**Issue by hreypar** [pepkit/pepspec#17]
Hi, I was studying the [PEP documentation](http://pep.databio.org/en/latest/specification/#project-config-file-specification) because I want to use it for a project and I was wondering if it wouldn't be better to remove `other_attr` from the `attributes` part of the derive sample modifier because there is no key3 so it's confusing. 

```
sample_modifiers:
    derive:
        attributes: [read1, read2, other_attr]
        sources: 
            key1: "path/to/derived/value/{attribute1}"
            key2: "path/to/derived/value/{attr2}"
```

Maybe I'm understanding the derive sample modifier wrong, so if the example config file is correct, I'd appreciate it if you could explain it to me. Thanks!
