### ISSUE TITLE
attributes with dots

### ISSUE THREAD

**Issue by fgvieira** [pepkit/pepspec#26]
Is it possible to have attribute names with dots?
For example:
```
pep_version: 2.1.0
sample_table: "samples.csv"
sample_modifiers:
  append:
    sample_name: name
  derive:
    attributes: ["sample_name"]
    sources:
      name: "{accession}_{assembly_info.assembly_name}"
```

Right now I get the error:
```
In sample 'name' cannot correctly parse derived attribute source: {accession}_{'assembly_info.assembly_name'}. Caught exception: 'str' object has no attribute 'assembly_name''
```
